name: Cashly CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  laravel-quality-check:
    runs-on: ubuntu-latest

    services:
      pgsql:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: cashly_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        healthcheck:
          test: ["CMD", "pg_isready", "-d", "cashly_test", "-U", "postgres"]
          interval: 10s
          timeout: 5s
          retries: 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 10s
          timeout: 5s
          retries: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, gd, zip, mysql, pdo_mysql, pdo_pgsql, redis
          tools: composer:v2, pint, phpstan
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create Testing Env
        run: |
          cp .env.example .env.testing
          php artisan key:generate --env=testing

      - name: Code Style (Pint)
        run: ./vendor/bin/pint --test

      - name: Static Analysis (PHPStan)
        run: ./vendor/bin/phpstan analyze

      - name: Run Migrations & Tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: cashly_test
          DB_USERNAME: postgres
          DB_PASSWORD: password
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: |
          php artisan migrate --env=testing --force
          php artisan test
